config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts
  devise_scope :account do
    get '/accounts/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do 
    resources :comments, only: [:new, :create]
    resource :like, only: [:create, :destroy]
  end 

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end
  resource :profile, only: [:show, :edit, :update]

  root to: 'posts#index'
end

app/views/commons/_post.html.haml
.post_list_card
  = link_to post_path(post) do
    .card_title
      = post.name
      .card_title_detail_date  
        %p= post.display_created_at
    .card_title_info
      = post.content
    .image_post_icon
      .post_edit_.button
        = link_to '編集', edit_post_path(post.id)
      .post_delete_button
        = link_to "削除", "posts/#{post.id}", data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
      .post_newimage_button
        = link_to '画像投稿', edit_post_path(post.id)
      - if account_signed_in? 
        -if current_account.has_liked?(post)
          .post_like_heart
            = link_to post_like_path(post), data: { method: 'delete' } do
              =image_tag 'Vector.svg'
        -else
          .post_like_heart
            = link_to post_like_path(post), data: { method: 'post' } do
              = image_tag 'heart.svg'
    .post_new_image_view
      = image_tag(post.image) if post.image.attached?

app/views/commons/_profile.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{current_account.display_name}（#{current_account.birthday}・#{current_account.gender}）
        .profilePage_account_follow_actionButton
          - if account == current_account
            = link_to 'Edit', edit_profile_path
          - else
            - if current_account&.has_followed?(account)
              = link_to 'Unfollow', account_unfollows_path(account), data: {method: 'post'}
            - else
              = link_to 'Follow', account_follows_path(account), data: {method: 'post'}
      .profilePage_user_introduction
        初めまして！
        = current_account.profile&.introduction
      .profilePage_user_introduction
      - current_account.posts.each do |post|
        = render 'commons/post', post: post