config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts
  devise_scope :account do
    get '/accounts/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do 
    resources :comments, only: [:new, :create]
    resource :like, only: [:create, :destroy]
  end 

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end
  resource :profile, only: [:show, :edit, :update]

  root to: 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy
    belongs_to :account, optional: true  

    def display_created_at
        I18n.l(self.created_at, format: :default)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  before_action :authenticate_account!, only: [:new, :create, :edit, :update, :destroy]
    
  def index
     @posts = Post.all
  end

  def show 
    @post = Post.find(params[:id])
    @comments = @post.comments
  end
  
  def edit 
    @post = current_account.posts.find(params[:id])
  end

  def new
    @post = current_account.posts.build
  end

  def create
      @post = current_account.posts.build(post_params)
      if @post.save!
          redirect_to posts_path(@post), notice: '保存できました'
        else
          flash.now[:error] = '保存に失敗しました'
          render :new
      end
  end

  def update
    @post = current_account.posts.find(params[:id])
    @post.update params.require(:post).permit(:name, :content, :image)
    if @post.update(post_params)
      redirect_to post_path(@post), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end
  
  def destroy
      @post =  current_account.posts.find(params[:id])
      @post.destroy!
      redirect_to posts_path(@post), notice: '削除に成功しました'
  end


  private
  def post_params
      params.require(:post).permit(:name, :content, :image)
  end
  def set_post
      @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.haml
.container
  = form_with(model: @post, url: post_path(@post),method: 'patch', local: true) do |f|
    %div
      = f.label :name, '名前' , class: 'text-edit-posts-name'
    %div
      = f.text_field :name, class: 'text-edit-posts-name-field'
    %div
      = f.label :'記事内容', class: 'text-edit-posts-content'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'
    %br/
  = form_with model: @post, local: true  do |form|
    = form.file_field :image
    %br/
    = form.submit '画像投稿'
    %br/

app/views/posts/index.html.haml
.post_list
  .post_list_title 投稿一覧
  .post_new
    = button_to '新規投稿はこちら', new_post_path, method: :get
  - @posts.each do |post|
    = render 'commons/post', post: post

app/views/posts/new.html.haml
.container
  %p 掲示板
  = form_with(model: @post, url: posts_path(@post), method: 'post', local: true) do |f|
    %div
      = f.label :name, '名前'
    %div
      = f.text_field :name, class: 'name'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    %div
      = f.file_field :image
    = f.submit '保存', class: 'btn-primary'

app/views/posts/show.html.haml
.post_list
.post_list_title 投稿詳細
.post_list_card
- if account_signed_in? && current_account.has_written?(@post)
  .post_detail_actions
    .dropdown1
      = image_tag 'actions.svg', class: 'dropbtn'
      .dropdown-content.mini
        = link_to '編集する', edit_post_path(@post)
        = link_to '削除する', post_path(@post), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
  .card_title_post
    = @post.name
  .card_title_info2_post
    = @post.content
  .post_list_top
    コメント一覧
    - @comments.each do |comment|
      .post_comment
        %p4= comment.content