config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts
  devise_scope :account do
    get '/accounts/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do 
    resources :comments, only: [:new, :create]
    resource :like, only: [:create, :destroy]
  end 

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end
  resource :profile, only: [:show, :edit, :update]

  root to: 'posts#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BulletinBoard
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  .header_logos
    - if !current_page?(root_path)
      = link_to :back do
        = image_tag 'back.jpg', class: 'header_back'
  .dropdown
  - if account_signed_in?
    .dropdown
      = image_tag 'default-avatar.png', class: 'header_avatar dropbtn'
      .dropdown-content
        = link_to 'プロフィール', profile_path
        = link_to 'ログアウト', destroy_account_session_path, data: { method: 'delete' }
  - else
    = link_to 'ログイン', new_account_session_path, class: 'header_loginBtn'
  .flash.time-limit
    %p
      = flash[:notice]
    %p.alert= alert  
    = yield
    